kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

spec:
  rules:
    {{- range .Values.domains }}
    - host: {{ . }}
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ $.Release.Name }}-service
                  port:
                    number: {{ $.Values.servicePort }}
    {{- end }}
  tls:
    - secretName: {{ .Release.Name }}-tls
      hosts:
        {{- range .Values.domains }}
        - {{ . }}
        {{- end }}
